# Generated by Django 4.2.7 on 2023-12-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destUserId', models.IntegerField()),
                ('time', models.CharField(max_length=20)),
                ('state', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MessageBox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('messages', models.JSONField()),
            ],
        ),
    ]
