# Generated by Django 4.2.5 on 2023-12-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promoter", models.IntegerField()),
                ("participants", models.JSONField()),
                ("minimum_participants", models.IntegerField()),
                ("maximum_participants", models.IntegerField()),
                ("date", models.CharField(max_length=50)),
                ("detail", models.CharField(max_length=200)),
                ("images", models.JSONField()),
                ("tags", models.JSONField()),
                ("state", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gym", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=20)),
                ("start", models.CharField(max_length=50)),
                ("end", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userid", models.CharField(max_length=20)),
                ("todos", models.JSONField()),
                ("partiActs", models.JSONField()),
                ("initiActs", models.JSONField()),
                ("appoints", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userid", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=100)),
                ("start", models.CharField(max_length=50)),
                ("end", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=20)),
                ("type", models.CharField(max_length=20)),
                ("state", models.IntegerField()),
                ("sportType", models.IntegerField()),
                ("sportState", models.CharField(max_length=20)),
            ],
        ),
    ]
