# Generated by Django 4.2.5 on 2023-12-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="userid",
        ),
        migrations.AddField(
            model_name="todo",
            name="date",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="todo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
