# Generated by Django 4.2.5 on 2023-12-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_remove_todo_userid_todo_date_alter_todo_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="id",
        ),
        migrations.AddField(
            model_name="todo",
            name="todoID",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
