# Generated by Django 4.2.5 on 2023-12-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0004_remove_todo_date_remove_todo_todoid_todo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="date",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
