# Generated by Django 4.2.5 on 2023-12-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0005_todo_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="maximum_participants",
            new_name="partNumMax",
        ),
        migrations.RenameField(
            model_name="activity",
            old_name="minimum_participants",
            new_name="partNumMin",
        ),
        migrations.AddField(
            model_name="activity",
            name="end",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="label",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="start",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="title",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todo",
            name="readOnly",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="todo",
            name="label",
            field=models.CharField(max_length=50),
        ),
    ]
