# Generated by Django 4.2.5 on 2023-12-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0006_rename_maximum_participants_activity_partnummax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="place",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
