# Generated by Django 4.2.5 on 2023-12-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0009_alter_todo_readonly"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commenterId", models.IntegerField()),
                ("activityId", models.IntegerField()),
                ("nickName", models.CharField(max_length=50)),
                ("avatarUrl", models.CharField(max_length=200)),
                ("comment", models.CharField(max_length=200)),
                ("likes", models.IntegerField()),
                ("likesID", models.JSONField()),
                ("pubTime", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="activity",
            name="place",
        ),
        migrations.AddField(
            model_name="activity",
            name="comments",
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="pubTime",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
