# Generated by Django 4.2.5 on 2023-12-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0010_comment_remove_activity_place_activity_comments_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applyerId", models.IntegerField()),
                ("actId", models.IntegerField()),
                ("message", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="activityId",
            new_name="actId",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="avatarUrl",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="nickName",
        ),
        migrations.AddField(
            model_name="schedule",
            name="applications",
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
