# Generated by Django 4.2.5 on 2023-12-18 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0012_todo_jodid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="jodId",
            new_name="jobId",
        ),
    ]
