# Generated by Django 4.2.5 on 2023-12-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0013_rename_jodid_todo_jobid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
