# Generated by Django 4.2.7 on 2023-11-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_userid_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatarUrl", models.CharField(max_length=200)),
                ("nickName", models.CharField(max_length=20)),
                ("signature", models.CharField(max_length=100)),
                ("followings", models.JSONField()),
                ("followingNum", models.IntegerField()),
                ("followers", models.JSONField()),
                ("followerNum", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatarUrl",
        ),
        migrations.AddField(
            model_name="user",
            name="userInfo",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.userinfo",
            ),
            preserve_default=False,
        ),
    ]
