# Generated by Django 4.2.7 on 2023-11-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_userinfo_remove_user_avatarurl_user_userinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="customSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("displayMode", models.IntegerField()),
                ("ddlRange", models.CharField(max_length=50)),
                ("storageRange", models.CharField(max_length=50)),
                ("blackList", models.JSONField()),
            ],
        ),
    ]
