# Generated by Django 4.2.5 on 2023-12-19 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_user_customsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="nickName",
        ),
    ]
