# Generated by Django 4.2.5 on 2023-12-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0003_remove_todo_id_todo_todoid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="date",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="todoID",
        ),
        migrations.AddField(
            model_name="todo",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
