# Generated by Django 4.2.7 on 2023-11-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=100)),
                ('avatarUrl', models.CharField(max_length=200)),
            ],
        ),
    ]
