# Generated by Django 4.2.7 on 2023-11-30 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_customsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="customSettings",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.customsettings",
            ),
            preserve_default=False,
        ),
    ]
