# Generated by Django 4.2.5 on 2023-12-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("floorNum", models.IntegerField()),
                ("userId", models.IntegerField()),
                ("name", models.CharField(max_length=20)),
                ("avatar", models.CharField(max_length=200)),
                ("time", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=200)),
                ("likes", models.IntegerField()),
                ("likeList", models.JSONField()),
                ("aboveId", models.IntegerField()),
                ("aboveName", models.CharField(max_length=20)),
                ("aboveContent", models.CharField(max_length=200)),
                ("belowIds", models.JSONField()),
                ("commentNum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userId", models.IntegerField()),
                ("name", models.CharField(max_length=20)),
                ("avatar", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=50)),
                ("time", models.CharField(max_length=50)),
                ("likes", models.IntegerField()),
                ("likeList", models.JSONField()),
                ("images", models.JSONField()),
                ("floorCnt", models.IntegerField()),
                ("floors", models.JSONField()),
            ],
        ),
    ]
